// <auto-generated />
using System;
using CompliXpertApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace CompliXpertApp.Migrations
{
    [DbContext(typeof(CompliXperAppContext))]
    partial class CompliXperAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("CompliXpertApp.Models.Account", b =>
                {
                    b.Property<int>("AccountNumber");

                    b.Property<string>("AccountClass");

                    b.Property<string>("AccountType");

                    b.Property<int?>("CustomerNumber");

                    b.HasKey("AccountNumber");

                    b.HasIndex("CustomerNumber");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("CompliXpertApp.Models.CallReport", b =>
                {
                    b.Property<int>("CallReportId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AccountNumber");

                    b.Property<string>("ApprovedBy");

                    b.Property<DateTime>("ApprovedDate");

                    b.Property<DateTime>("CallDate");

                    b.Property<bool>("CreatedOnMobile");

                    b.Property<string>("CustomerComments");

                    b.Property<string>("CustomerResponse");

                    b.Property<string>("LastUpdated");

                    b.Property<DateTime>("LastUpdatedDate");

                    b.Property<string>("Nationality");

                    b.Property<string>("Officer");

                    b.Property<string>("OfficerComments");

                    b.Property<string>("OtherComments");

                    b.Property<string>("Position");

                    b.Property<string>("Purpose");

                    b.Property<string>("Reason");

                    b.Property<string>("ReasonforAlert");

                    b.Property<string>("Reference");

                    b.Property<string>("Status");

                    b.HasKey("CallReportId");

                    b.HasIndex("AccountNumber");

                    b.ToTable("CallReport");
                });

            modelBuilder.Entity("CompliXpertApp.Models.Customer", b =>
                {
                    b.Property<int>("CustomerNumber");

                    b.Property<int>("CustomerId");

                    b.Property<string>("CustomerName");

                    b.Property<string>("LegalType");

                    b.HasKey("CustomerNumber");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("CompliXpertApp.Models.Account", b =>
                {
                    b.HasOne("CompliXpertApp.Models.Customer", "CustomerNumberNavigation")
                        .WithMany("Account")
                        .HasForeignKey("CustomerNumber");
                });

            modelBuilder.Entity("CompliXpertApp.Models.CallReport", b =>
                {
                    b.HasOne("CompliXpertApp.Models.Account", "AccountNumberNavigation")
                        .WithMany("CallReport")
                        .HasForeignKey("AccountNumber")
                        .HasConstraintName("FK__CallRepor__Accou__59063A47");
                });
#pragma warning restore 612, 618
        }
    }
}
